//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pekarna_Xlebus
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_transactions
    {
        public int transaction_id { get; set; }
        public int product_id { get; set; }
        public int quantity_change { get; set; }
        public string transaction_type { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public string notes { get; set; }
    
        public virtual products products { get; set; }
    }
}
