//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pekarna_Xlebus
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.inventory_transactions = new HashSet<inventory_transactions>();
            this.order_items = new HashSet<order_items>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string barcode { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> supplier_id { get; set; }
        public decimal unit_price { get; set; }
        public int stock_quantity { get; set; }
        public Nullable<int> reorder_level { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual categories categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_transactions> inventory_transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_items> order_items { get; set; }
        public virtual suppliers suppliers { get; set; }
    }
}
